server:
  port: 9091

spring:
  application:
    name: sentinel-core
  cloud:
    sentinel:
      transport:
        dashboard: 120.27.11.244:9124
        clientIp: localhost
      eager: true
      web-context-unify: true
      datasource:
        - ds1:
            file:
              file: classpath:flowrule.json
              data-type: json
              rule-type: flow
        - ds2:
            file:
              file: classpath:degraderule.json
              data-type: json
              rule-type: degrade
        - ds3:
            file:
              file: classpath:authority.json
              rule-type: authority
        - ds3:
            file:
              file: classpath:system.json
              rule-type: system
        - ds5:
            file:
              file: classpath:param-flow.json
              rule-type: param-flow

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false



