spring:
  application:
    name: nacos-discovery-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 120.27.11.244:9123
      username: nacos
      password: nacos
#    sentinel:
#      transport:
#        dashboard: 120.27.11.244:9124
#      eager: true
#      datasource:
#        ds1:
#          file:
#            file: 'classpath: flowrule.json'
#          data-type: json
#          rule-type: flow


feign:
  sentinel:
    enabled: true

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: '*'


