server:
  port: 8087
spring:
  application:
    name: nacos-gateway-provider
  cloud:
    nacos:
      discovery:
        server-addr: 120.27.11.244:9123
      username: naocs
      password: nacos
management:
  endpoints:
    web:
      exposure:
        include: '*'
