spring:
  application:
    name: sentinel-dubbo-consumer

service:
  version: 1.0.0
dubbo:
  application:
    id: sentinel-dubbo-provider
    name: sentinel-dubbo-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
